name: Test Changed Jupyter Notebooks

on:
  pull_request:
    branches:
      - main

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        echo "::error::Filename doesn't match possible files" && exit 1
      shell: bash
