name: Test Changed Jupyter Notebooks

on:
  pull_request:
    branches:
      - main

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install -y git
      shell: bash

    - name: Install libgraphviz-dev
      run: sudo apt-get install -y libgraphviz-dev
      shell: bash

    - name: Install R
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use Python 3.10

    - name: Install dependencies
      run: |
        echo "message=Installing-Dependencies" >> $GITHUB_OUTPUT
        echo "::error file=test"
      shell: bash
