name: Run Jupyter Notebooks

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs once a week on Sunday at midnight

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust this to your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        pip install -r requirements.txt

    - name: Convert Jupyter notebooks to Python scripts
      run: |
        find . -name "*.ipynb" -exec jupyter nbconvert --to script {} \;

    - name: Run Python scripts
      run: |
        find . -name "*.py" -exec python {} \;
