name: Run Jupyter Notebooks

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs once a week on Sunday at midnight

jobs:
  run-notebooks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust this to your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert flake8 ipython
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Convert Jupyter notebooks to Python scripts
      run: |
        find . -name "PM1/*.ipynb" -exec jupyter nbconvert --to script {} \;
      shell: bash

    - name: Run Flake8 linting
      run: |
        find . -name "PM1/*.py" -exec flake8 {} \;
      shell: bash

    - name: Run Python scripts with IPython
      run: |
        mkdir -p logs
        find . -name "PM1/*.py" -exec sh -c '
          for script; do
            echo "Running $script"
            ipython $script > "logs/$(basename $script .py).log" 2>&1 || true
          done
        ' sh {} +
      shell: bash

    - name: Aggregate and report errors and warnings
      run: |
        echo "Aggregating errors and warnings..."
        grep -E "Error|Warning" logs/*.log > logs/errors_and_warnings.log || true
        echo "Errors and Warnings:"
        cat logs/errors_and_warnings.log
      shell: bash
