name: Convert R Notebooks to Rmd and R Scripts

on:
  push

jobs:
  convert-irnb-to-rmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install rmarkdown and knitr packages
      run: |
        R -e 'install.packages(c("rmarkdown", "knitr", "xfun"), repos="https://cloud.r-project.org")'

    - name: Convert .irnb to .Rmd and .R
      run: |
        R -e '
          files <- list.files(path = "PM1", pattern = "\\.irnb$", full.names = TRUE, recursive = FALSE)
          lapply(files, function(input) {
            rmarkdown::convert_ipynb(input)
            rmd_file <- xfun::with_ext(input, "Rmd")
            knitr::purl(rmd_file, output = xfun::with_ext(input, "R"))
          })
        '

    - name: Zip .R files
      run: |
        mkdir r_scripts
        mv PM1/*.R r_scripts/
        zip -r r_scripts.zip r_scripts

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: r-scripts
        path: r_scripts.zip

    - name: Commit and push .Rmd files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add PM1/*.Rmd  # Update this path to your directory
        git commit -m 'Convert .irnb to .Rmd'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
